[2024-11-12T21:33:46.450+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T21:33:46.462+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Stock_Prediction.predict manual__2024-11-12T21:31:43.347636+00:00 [queued]>
[2024-11-12T21:33:46.465+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Stock_Prediction.predict manual__2024-11-12T21:31:43.347636+00:00 [queued]>
[2024-11-12T21:33:46.466+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-12T21:33:46.470+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): predict> on 2024-11-12 21:31:43.347636+00:00
[2024-11-12T21:33:46.474+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=32148) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-12T21:33:46.475+0000] {standard_task_runner.py:63} INFO - Started process 32151 to run task
[2024-11-12T21:33:46.474+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Stock_Prediction', 'predict', 'manual__2024-11-12T21:31:43.347636+00:00', '--job-id', '168', '--raw', '--subdir', 'DAGS_FOLDER/FinanceDataAnalytics_Prediction_Pair9.ipynb.py', '--cfg-path', '/tmp/tmpbb68a_ks']
[2024-11-12T21:33:46.476+0000] {standard_task_runner.py:91} INFO - Job 168: Subtask predict
[2024-11-12T21:33:46.495+0000] {task_command.py:426} INFO - Running <TaskInstance: Stock_Prediction.predict manual__2024-11-12T21:31:43.347636+00:00 [running]> on host 2538ecb7b4d3
[2024-11-12T21:33:46.531+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='shatayu.thakur@sjsu.edu' AIRFLOW_CTX_DAG_OWNER='Pair 9' AIRFLOW_CTX_DAG_ID='Stock_Prediction' AIRFLOW_CTX_TASK_ID='predict' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T21:31:43.347636+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-12T21:31:43.347636+00:00'
[2024-11-12T21:33:46.532+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T21:33:46.536+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-11-12T21:33:46.537+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.0, Python Version: 3.12.3, Platform: Linux-6.10.11-linuxkit-aarch64-with-glibc2.36
[2024-11-12T21:33:46.537+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-11-12T21:34:06.650+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-12T21:34:07.876+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-12T21:34:07.877+0000] {connection.py:762} INFO - closed
[2024-11-12T21:34:07.919+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-11-12T21:34:08.001+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-12T21:34:08.004+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T21:34:08.023+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Stock_Prediction, task_id=predict, run_id=manual__2024-11-12T21:31:43.347636+00:00, execution_date=20241112T213143, start_date=20241112T213346, end_date=20241112T213408
[2024-11-12T21:34:08.024+0000] {taskinstance.py:1182} ERROR - Error when executing notify_stock_prediction_success callback
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1179, in _run_finished_callback
    callback(context)
  File "/opt/airflow/dags/FinanceDataAnalytics_Prediction_Pair9.ipynb.py", line 21, in notify_stock_prediction_success
    send_slack_notification(f"Stock_Prediction DAG {context['dag'].dag_id} succeeded!")
    ^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'send_slack_notification' is not defined
[2024-11-12T21:34:08.077+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-12T21:34:08.092+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-12T21:34:08.094+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
