[2024-11-15T07:24:24.809+0000] {processor.py:161} INFO - Started process (PID=295) to work on /opt/airflow/dags/FinanceDataAnalytics_ELT.py
[2024-11-15T07:24:24.809+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/FinanceDataAnalytics_ELT.py for tasks to queue
[2024-11-15T07:24:24.811+0000] {logging_mixin.py:188} INFO - [2024-11-15T07:24:24.811+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/FinanceDataAnalytics_ELT.py
[2024-11-15T07:24:24.823+0000] {logging_mixin.py:188} INFO - [2024-11-15T07:24:24.822+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/FinanceDataAnalytics_ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/FinanceDataAnalytics_ELT.py", line 13, in <module>
    conn = BaseHook.get_connection('snowflake_conn')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2024-11-15T07:24:24.824+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/FinanceDataAnalytics_ELT.py
[2024-11-15T07:24:24.830+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/FinanceDataAnalytics_ELT.py took 0.026 seconds
[2024-11-15T07:24:55.194+0000] {processor.py:161} INFO - Started process (PID=338) to work on /opt/airflow/dags/FinanceDataAnalytics_ELT.py
[2024-11-15T07:24:55.194+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/FinanceDataAnalytics_ELT.py for tasks to queue
[2024-11-15T07:24:55.196+0000] {logging_mixin.py:188} INFO - [2024-11-15T07:24:55.195+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/FinanceDataAnalytics_ELT.py
[2024-11-15T07:24:55.205+0000] {logging_mixin.py:188} INFO - [2024-11-15T07:24:55.204+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/FinanceDataAnalytics_ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/FinanceDataAnalytics_ELT.py", line 13, in <module>
    conn = BaseHook.get_connection('snowflake_conn')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2024-11-15T07:24:55.205+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/FinanceDataAnalytics_ELT.py
[2024-11-15T07:24:55.210+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/FinanceDataAnalytics_ELT.py took 0.020 seconds
[2024-11-15T07:25:25.599+0000] {processor.py:161} INFO - Started process (PID=359) to work on /opt/airflow/dags/FinanceDataAnalytics_ELT.py
[2024-11-15T07:25:25.601+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/FinanceDataAnalytics_ELT.py for tasks to queue
[2024-11-15T07:25:25.602+0000] {logging_mixin.py:188} INFO - [2024-11-15T07:25:25.602+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/FinanceDataAnalytics_ELT.py
[2024-11-15T07:25:25.612+0000] {logging_mixin.py:188} INFO - [2024-11-15T07:25:25.611+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/FinanceDataAnalytics_ELT.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/FinanceDataAnalytics_ELT.py", line 13, in <module>
    conn = BaseHook.get_connection('snowflake_conn')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2024-11-15T07:25:25.612+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/FinanceDataAnalytics_ELT.py
[2024-11-15T07:25:25.616+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/FinanceDataAnalytics_ELT.py took 0.021 seconds
